### PR TITLE
User logout redirect

### PR DESCRIPTION
**Pull request by willrax**
Changed the logout link to redirect to the login screen after destroying the user session.

### CODE REVIEW

**Comment by HashNuke** [comment]
@kevzettler I just checked this. Good to merge.

**Comment by kevzettler** [comment]
@HashNuke 

Any idea if this will effect the casfuji logout flow?

```
def after_sign_out_path_for(resource_or_scope)      
  root_path     
end
```

**Comment by HashNuke** [comment]
no it wont. it's just using the rails helper for links. 

## 

Akash Manohar J
http://akash.im
@HashNuke

**Comment by HashNuke** [comment]
Also devise logout now requires DELETE request to logout. (it was GET in the older versions). This pull request fixes that too. 

## 

Akash Manohar J
http://akash.im
@HashNuke

**Comment by HashNuke** [comment]
This fixes #5

**Comment by willrax** [comment]
@kevzettler @HashNuke 

i think it turned out that 

```
def after_sign_out_path_for(resource_or_scope)      
  root_path     
end
```

wasn't needed in the end.

**Comment by kevzettler** [comment]
@willrax 

Can we drop it from the pull request then?

**Comment by willrax** [comment]
@kevzettler fixed

**Comment by kevzettler** [comment]
closes #5

**Comment by MichaelEvans** [comment]
Shouldn't `:method => :destroy` be `:method => :delete`?

**Comment by HashNuke** [comment]
@MichaelEvans agree. the devise http request method for logout is :delete

**Pull request merged**
